exports.finishes = [
  {
    name: "Brushed Bronze",
    slug: "brushed-bronze",
    image: "images/finishes/brushed_bronze.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Polished Nickel",
    slug: "polished-nickel",
    image: "images/finishes/polished_nickle.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Satin Brass",
    slug: "satin-brass",
    image: "images/finishes/satin_brass.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Matte Black",
    slug: "matte-black",
    image: "images/finishes/matte_black.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Oil Rubbed Bronze",
    slug: "oil-rubbed-bronze",
    image: "images/finishes/oil_rubbed_bronze.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Brushed Nickel",
    slug: "brushed-nickel",
    image: "images/finishes/brushed_nickle.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
  {
    name: "Polished Chrome",
    slug: "polished-chrome",
    image: "images/finishes/polished_chrome.jpeg",
    partNumber: "1",
    holesNeeded: 1,
    cost: 0.0,
    thickness: "both",
    // status: true,
  },
];
