exports.hardwares = [
  {
    name: "Victorian 8x8 Pull",
    image: "images/hardwares/default.png",
    slug: "victorian-8x8-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "8 x 8 MT Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-mt-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "8 x 8 Colonial Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-colonial-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "8 x 8 Square Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-square-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "8 X 8 D-Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-d-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "8x8 Ladder Pull",
    image: "images/hardwares/default.png",
    slug: "8x8-ladder-pull",
    hardware_category_slug: "handles",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "HVY Pivot Bevel",
    image: "images/hardwares/default.png",
    slug: "hvy-pivot-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Sleeve Over Pivot (PPH07)",
    image: "images/hardwares/default.png",
    slug: "sleeve-over-pivot-pph07",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Offset HVY Bevel",
    image: "images/hardwares/default.png",
    slug: "offset-hvy-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Offset STD Bevel",
    image: "images/hardwares/default.png",
    slug: "offset-std-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Pivot Bevel",
    image: "images/hardwares/default.png",
    slug: "pivot-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "HVY Square",
    image: "images/hardwares/default.png",
    slug: "hvy-square",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "STD Bevel",
    image: "images/hardwares/default.png",
    slug: "std-bevel",
    hardware_category_slug: "hinges",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "U-Channel (1/2)",
    image: "images/hardwares/default.png",
    slug: "u-channel-1-2",
    hardware_category_slug: "mounting-channels",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "U-Channel (3/8)",
    image: "images/hardwares/default.png",
    slug: "u-channel-3-8",
    hardware_category_slug: "mounting-channels",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Corner Clamp",
    image: "images/hardwares/default.png",
    slug: "corner-clamp",
    hardware_category_slug: "mounting-clamps",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Beveled Wall Clamp",
    image: "images/hardwares/default.png",
    slug: "beveled-wall-clamp",
    hardware_category_slug: "mounting-clamps",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Operable wall Clamp",
    image: "images/hardwares/default.png",
    slug: "operable-wall-clamp",
    hardware_category_slug: "transom",
    operableTransom: true,
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Fixed Wall Clamp",
    image: "images/hardwares/default.png",
    slug: "fixed-wall-clamp",
    hardware_category_slug: "transom",
    // operableTransom:true,
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Fixed Glass To Glass Clamp",
    image: "images/hardwares/default.png",
    slug: "fixed-glass-to-glass-clamp",
    hardware_category_slug: "transom",
    // operableTransom:true,
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Operable Glass To Glass Clamps",
    image: "images/hardwares/default.png",
    slug: "operable-glass-to-glass-clamps",
    hardware_category_slug: "transom",
    operableTransom: true,
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: 'Cardinal Skyline (84")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-84",
    hardware_category_slug: "sliding-door-system",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: 'Cardinal Skyline (72")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-72",
    hardware_category_slug: "sliding-door-system",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Capitol",
    image: "images/hardwares/default.png",
    slug: "capitol",
    hardware_category_slug: "sliding-door-system",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Cambridge",
    image: "images/hardwares/default.png",
    slug: "cambridge",
    hardware_category_slug: "sliding-door-system",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: 'Cardinal Skyline (60")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-60",
    hardware_category_slug: "sliding-door-system",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: '144" Header',
    image: "images/hardwares/default.png",
    slug: "144-header",
    hardware_category_slug: "header",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: '98" Header',
    image: "images/hardwares/default.png",
    slug: "98-header",
    hardware_category_slug: "header",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: '66" Header',
    image: "images/hardwares/default.png",
    slug: "66-header",
    hardware_category_slug: "header",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Towel Bars",
    image: "images/hardwares/default.png",
    slug: "towel-bars",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Sleeve Over",
    image: "images/hardwares/default.png",
    slug: "sleeve-over",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Offset HVY Clamps",
    image: "images/hardwares/default.png",
    slug: "offset-hvy-clamps",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Sandblasting",
    image: "images/hardwares/default.png",
    slug: "sandblasting",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Sandblasting",
    image: "images/hardwares/default.png",
    slug: "sandblasting",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
  {
    name: "Grids",
    image: "images/hardwares/default.png",
    slug: "grids",
    hardware_category_slug: "add-ons",
    finishes: [
      {
        name: "Brushed Bronze",
        image: "images/finishes/brushed_bronze.jpeg",
        cost: 10,
        status: true,
        finish_id: "brushed-bronze",
      },
      {
        name: "Polished Nickel",
        image: "images/finishes/polished_nickle.jpeg",
        cost: 12,
        status: true,
        finish_id: "polished-nickel",
      },
      {
        name: "Satin Brass",
        image: "images/finishes/satin_brass.jpeg",
        cost: 14,
        status: true,
        finish_id: "satin-brass",
      },
      {
        name: "Matte Black",
        image: "images/finishes/matte_black.jpeg",
        cost: 16,
        status: true,
        finish_id: "matte-black",
      },
      {
        name: "Oil Rubbed Bronze",
        image: "images/finishes/oil_rubbed_bronze.jpeg",
        cost: 18,
        status: true,
        finish_id: "oil-rubbed-bronze",
      },
      {
        name: "Brushed Nickel",
        image: "images/finishes/brushed_nickle.jpeg",
        cost: 20,
        status: true,
        finish_id: "brushed-nickel",
      },
      {
        name: "Polished Chrome",
        image: "images/finishes/polished_chrome.jpeg",
        cost: 22,
        status: true,
        finish_id: "polished-chrome",
      },
    ],
  },
];
