exports.hardwares = [
  {
    name: "Victorian 8x8 Pull",
    image: "images/hardwares/default.png",
    slug: "victorian-8x8-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "8 x 8 MT Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-mt-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "8 x 8 Colonial Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-colonial-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "8 x 8 Square Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-square-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "8 X 8 D-Pull",
    image: "images/hardwares/default.png",
    slug: "8-x-8-d-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "8x8 Ladder Pull",
    image: "images/hardwares/default.png",
    slug: "8x8-ladder-pull",
    hardware_category_slug: "handles",
  },
  {
    name: "HVY Pivot Bevel",
    image: "images/hardwares/default.png",
    slug: "hvy-pivot-bevel",
    hardware_category_slug: "hinges",
  },
  {
    name: "Sleeve Over Pivot (PPH07)",
    image: "images/hardwares/default.png",
    slug: "sleeve-over-pivot-pph07",
    hardware_category_slug: "hinges",
  },
  {
    name: "Offset HVY Bevel",
    image: "images/hardwares/default.png",
    slug: "offset-hvy-bevel",
    hardware_category_slug: "hinges",
  },
  {
    name: "Offset STD Bevel",
    image: "images/hardwares/default.png",
    slug: "offset-std-bevel",
    hardware_category_slug: "hinges",
  },
  {
    name: "Pivot Bevel",
    image: "images/hardwares/default.png",
    slug: "pivot-bevel",
    hardware_category_slug: "hinges",
  },
  {
    name: "HVY Square",
    image: "images/hardwares/default.png",
    slug: "hvy-square",
    hardware_category_slug: "hinges",
  },
  {
    name: "STD Bevel",
    image: "images/hardwares/default.png",
    slug: "std-bevel",
    hardware_category_slug: "hinges",
  },
  {
    name: "U-Channel (1/2)",
    image: "images/hardwares/default.png",
    slug: "u-channel-1-2",
    hardware_category_slug: "mounting-channels",
  },
  {
    name: "U-Channel (3/8)",
    image: "images/hardwares/default.png",
    slug: "u-channel-3-8",
    hardware_category_slug: "mounting-channels",
  },
  {
    name: "Corner Clamp",
    image: "images/hardwares/default.png",
    slug: "corner-clamp",
    hardware_category_slug: "mounting-clamps",
  },
  {
    name: "Beveled Wall Clamp",
    image: "images/hardwares/default.png",
    slug: "beveled-wall-clamp",
    hardware_category_slug: "mounting-clamps",
  },
  {
    name: "Operable wall Clamp",
    image: "images/hardwares/default.png",
    slug: "operable-wall-clamp",
    hardware_category_slug: "transom",
    operableTransom: true,
  },
  {
    name: "Fixed Wall Clamp",
    image: "images/hardwares/default.png",
    slug: "fixed-wall-clamp",
    hardware_category_slug: "transom",
    // operableTransom:true,
  },
  {
    name: "Fixed Glass To Glass Clamp",
    image: "images/hardwares/default.png",
    slug: "fixed-glass-to-glass-clamp",
    hardware_category_slug: "transom",
    // operableTransom:true,
  },
  {
    name: "Operable Glass To Glass Clamps",
    image: "images/hardwares/default.png",
    slug: "operable-glass-to-glass-clamps",
    hardware_category_slug: "transom",
    operableTransom: true,
  },
  {
    name: 'Cardinal Skyline (84")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-84",
    hardware_category_slug: "sliding-door-system",
  },
  {
    name: 'Cardinal Skyline (72")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-72",
    hardware_category_slug: "sliding-door-system",
  },
  {
    name: "Capitol",
    image: "images/hardwares/default.png",
    slug: "capitol",
    hardware_category_slug: "sliding-door-system",
  },
  {
    name: "Cambridge",
    image: "images/hardwares/default.png",
    slug: "cambridge",
    hardware_category_slug: "sliding-door-system",
  },
  {
    name: 'Cardinal Skyline (60")',
    image: "images/hardwares/default.png",
    slug: "cardinal-skyline-60",
    hardware_category_slug: "sliding-door-system",
  },
  {
    name: '144" Header',
    image: "images/hardwares/default.png",
    slug: "144-header",
    hardware_category_slug: "header",
  },
  {
    name: '98" Header',
    image: "images/hardwares/default.png",
    slug: "98-header",
    hardware_category_slug: "header",
  },
  {
    name: '66" Header',
    image: "images/hardwares/default.png",
    slug: "66-header",
    hardware_category_slug: "header",
  },
];
